import { openai } from "@/lib/openai";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        const { prompt } = await req.json();

        if (!prompt) {
            return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
        }

        const response = await openai.images.generate({
            model: "dall-e-3",
            prompt: `${prompt} The image should be photorealistic, high-end grooming studio background, cinematic lighting.`,
            n: 1,
            size: "1024x1024",
            quality: "standard",
        });

        if (!response.data || response.data.length === 0 || !response.data[0].url) {
            throw new Error("No image was generated by OpenAI");
        }

        return NextResponse.json({ url: response.data[0].url });
    } catch (error) {
        console.error("DALL-E Generation Error:", error);
        return NextResponse.json({ error: "Generation failed" }, { status: 500 });
    }
}
