import { StyleOption, Product } from "../types";

export const STYLE_OPTIONS: StyleOption[] = [
    {
        id: "Teddy Bear",
        name: "클래식 테디베어",
        description: "동글동글한 얼굴과 귀로 거부할 수 없는 귀여움을 선사합니다.",
        image: "/images/styles/teddy_bear.png",
    },
    {
        id: "Formal Tuxedo",
        name: "블랙 타이 포멀",
        description: "세련된 블랙 턱시도와 강렬한 레드 보타이로 격식 있는 룩을 완성합니다.",
        image: "/images/styles/formal_tuxedo.png",
    },
    {
        id: "Streetwear",
        name: "어반 스트릿",
        description: "트렌디한 후디와 미니 선글라스로 힙한 감성을 더합니다.",
        image: "/images/styles/streetwear.png",
    },
    {
        id: "Hawaiian",
        name: "알로하 바캉스",
        description: "시원한 트로피컬 셔츠와 밀짚 모자로 해변의 분위기를 냅니다.",
        image: "/images/styles/hawaiian.png",
    },
    {
        id: "custom",
        name: "나만의 스타일",
        description: "상상하는 무엇이든 만들어드립니다",
        image: "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?q=80&w=300&h=300&auto=format&fit=crop", // Keep unsplash for custom or generate one later
    },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "p1",
        name: "코지 테디 양털 베스트",
        description: "포근한 양털 소재로 보온성과 귀여움을 동시에!",
        price: 24000,
        image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p2",
        name: "프리미엄 로열 턱시도",
        description: "특별한 날을 위한 최고의 정장 세트입니다.",
        price: 45000,
        image: "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p3",
        name: "어반 네온 스트릿 후디",
        description: "비비드한 컬러로 산책길의 주인공이 되어보세요.",
        price: 29000,
        image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p4",
        name: "알로하 트로피컬 셔츠",
        description: "시원한 소재와 화려한 패턴의 바캉스 룩.",
        price: 19500,
        image: "https://images.unsplash.com/photo-1591769225440-811ad7d63ca2?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p5",
        name: "클래식 트위드 자켓",
        description: "고급스러운 무드의 패셔니스타 필수 아이템.",
        price: 58000,
        image: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p6",
        name: "스포티 매쉬 저지",
        description: "활동성이 뛰어난 통기성 만점 기능성 저지.",
        price: 22000,
        image: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p7",
        name: "레인보우 소프트 니트",
        description: "화사한 컬러감이 돋보이는 부드러운 스웨터.",
        price: 32000,
        image: "https://images.unsplash.com/photo-1620948871199-07380905156a?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "p8",
        name: "빈티지 데님 오버롤",
        description: "어떤 이너와 매치해도 귀여운 복고풍 스타일.",
        price: 36000,
        image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Clothing",
    },
    {
        id: "a1",
        name: "럭셔리 펄 넥클리스",
        description: "우아함을 더해주는 진주 포인트 목걸이.",
        price: 12000,
        image: "https://images.unsplash.com/photo-1614859324967-bdf281f45595?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Accessory",
    },
    {
        id: "a2",
        name: "어반 쿨 선글라스",
        description: "자외선 차단과 힙한 감성을 동시에!",
        price: 15000,
        image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Accessory",
    },
    {
        id: "a3",
        name: "로맨틱 리본 케이프",
        description: "공주님, 왕자님으로 만들어주는 마법의 케이프.",
        price: 18000,
        image: "https://images.unsplash.com/photo-1583512603806-077998240c7a?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Accessory",
    },
    {
        id: "a4",
        name: "윈터 체크 머플러",
        description: "추운 날씨에도 따뜻하고 스타일리시하게.",
        price: 9900,
        image: "https://images.unsplash.com/photo-1522276492509-df418579b946?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Accessory",
    },
    {
        id: "a5",
        name: "베이직 코튼 비니",
        description: "귀여운 귀 구멍이 있는 편안한 비니 모자.",
        price: 11000,
        image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?q=80&w=400&h=500&auto=format&fit=crop",
        url: "https://www.coupang.com/",
        category: "Accessory",
    },
];
